spring:
  config:
    activate:
      on-profile: default
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster0.awggt.mongodb.net/alloyIntegrationDBtest
      database: alloyIntegrationDB
      authentication-database: admin
      auto-index-creation: true

alloy:
  api:
    baseUrl: https://sandbox.alloy.co/v1
    username: ${ALLOY_USERNAME}
    password: ${ALLOY_PASSWORD}

feign:
  client:
    name: feignClient