spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    mongodb:
      database: alloyIntegrationDB
      authentication-database: admin
      host: localhost
      port: 27017

alloy:
  api:
    baseUrl: https://sandbox.alloy.co/v1
    username: ${CREDS_USERNAME}
    password: ${CREDS_PASSWORD}

feign:
  client:
    name: feignClient
