package com.github.daniilandco.alloyintegration.config;

import feign.RequestInterceptor;
import feign.auth.BasicAuthRequestInterceptor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Configuration class for setting up external API calls functionality with Feign client.
 *
 * @author com.github.daniilandco
 * @version 1.0
 */
@Configuration
public class FeignClientConfig {
    @Value("${alloy.api.username}")
    private String username;
    @Value("${alloy.api.password}")
    private String password;

    /**
     * Adds valid headers to each request done by Feign client.
     * Content-type -> application/json.
     * Accept -> application/json.
     *
     * @return RequestInterceptor instance which is set up to include valid headers for each request
     */
    @Bean
    public RequestInterceptor requestInterceptor() {
        return requestTemplate -> {
            requestTemplate.header("Content-Type", "application/json");
            requestTemplate.header("Accept", "application/json");
        };
    }

    /**
     * Returns BasicAuthRequestInterceptor instance with valid auth creds for accessing to Alloy API.
     *
     * @return BasicAuthRequestInterceptor instance which adds header Authorization with basic auth token
     * generated by passed username and password
     */
    @Bean
    public BasicAuthRequestInterceptor basicAuthRequestInterceptor() {
        return new BasicAuthRequestInterceptor(username, password);
    }
}
